title: "Azevedo Lablet"
email: tazevedo@uw.edu
timezone: UTC
baseurl: "" # "/affiliates-jekyll-theme"
url: "https://tony-azevedo.github.io"
permalink: "/:title/"
theme: "minima"
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# author: Sal
# paginate: 30
# disqus: 'demowebsite'
locale: en_us
lang: en_us
# feed_items: 10
# feed_update_period: daily
# feed_update_frequency: 1
# markdown: kramdown
# kramdown:
#   syntax_highlighter_opts:
#     disable: true
# sass:
#   sass_dir: _sass
#   style: :compressed
# ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
  tony:
    name: Tony
    display_name: Tony
    avatar: 'assets/images/tony.jpg'
    email: tazevedo@uw.edu
    description: "A sentient being made of God knows what."

# Social
social:
  # linkedin: https://linkedin.com/in/tonyazevedo
  github: https://github.com/tony-azevedo

# Plugins
# - jekyll-paginate
plugins: 
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag

# jekyll-feed
# jekyll-seo-tag
# jekyll-sitemap
# jekyll-paginate
# jekyll-coffeescript
# jekyll-default-layout
# jekyll-gist
# jekyll-github-metadata
# jekyll-optional-front-matter
# jekyll-readme-index
# jekyll-redirect-from
# jekyll-relative-links
# jekyll-remote-theme
# jekyll-titles-from-headings